Fix deprecation warning in `snippet-java-fixtures_kotlin_javaTestFixtures.sample`
Because of an unexpected output:

```
java.lang.AssertionError: Unexpected value at line 2.
Expected: > Task :dependencyInsight
Actual: > Configure project :lib
Actual output:
> Configure project :lib
w: file:///home/user/gradle/samples/lib/build.gradle.kts:51:7: 'create(String!, Action<in Task!>!): Task!' is deprecated. Deprecated in Java
```