Fix DaemonToolchainCoexistWithCurrentOptionsCrossVersionTest
https://github.com/gradle/gradle/pull/33384 changes the behavior of `AvailableJavaHomes.getDifferentVersion`, which now returns JDK 24. It caused some Groovy compilation error: https://ge.gradle.org/s/vyo7effvmlygq/tests/task/:tooling-api:gradle8.10.2CrossVersionTest/details/org.gradle.integtests.tooling.r88.DaemonToolchainCoexistWithCurrentOptionsCrossVersionTest/Given%20defined%20org.gradle.java.home%20gradle%20property%20When%20using%20daemon%20toolchain%20Then%20option%20is%20ignored%20resolving%20with%20expected%20toolchain%20TAPI%20current%20-%3E%20Gradle%208.10.2?focused-exception-line=0-1-2-0&top-execution=2

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 68
```

This PR fixes by making sure the test Java is below 24.

Co-authored-by: Bo Zhang <bo@gradle.com>