Fix Idea Groovyc java.lang.NoClassDefFoundError problem
- remove gradle build directories from all scopes
  - keep build/generated-resources/main since it
    contains the required *-classpath.properties files
    - required by DefaultModuleRegistry
- remove resources from Idea runtime and test scopes
  - replace with java-resource / java-test-resource