Capture exceptions thrown in JavaProcessStackTracesMonitor
We found some exceptions in JavaProcessStackTracesMonitor:

```
Caused by:
java.lang.IllegalThreadStateException: process has not exited
    at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:553)
    at org.gradle.integtests.fixtures.timeout.JavaProcessStackTracesMonitor.run(JavaProcessStackTracesMonitor.java:233)
    at org.gradle.integtests.fixtures.timeout.JavaProcessStackTracesMonitor$JavaProcessInfo.jstack(JavaProcessStackTracesMonitor.java:133)
    ...
```

Whic blocks fetching stack dumps for other JVMs.