Avoid `ImmutableSet.of` on Groovy for Java 9
As it was causing:

    java.lang.IncompatibleClassChangeError: Method java.util.Set.of(Ljava/lang/Object;)Ljava/util/Set; must be InterfaceMethodref constant