Remove check if nativeBaseDir for NativeServices exist
This caused problems in tests in buildSrc on linux, since the nativeBaseDir was set to another directory on the second test but the services have not been initialized. The Exception was:
java.lang.IllegalStateException: NativeServices initialized for directory that no longer exists: /tmp/gradle7988543280986374761projectDir/userHome
    at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:92)
    at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:61)
    at org.gradle.testfixtures.internal.ProjectBuilderImpl.createProject(ProjectBuilderImpl.java:74)
    at org.gradle.testfixtures.ProjectBuilder.build(ProjectBuilder.java:112)
    at org.gradle.build.docs.dsl.source.ExtractDslMetaDataTaskTest.$spock_initializeFields(ExtractDslMetaDataTaskTest.groovy:24

 in org.gradle.cleanup.EmptyDirectoryCheckTest