Used fixed versions for build init templates
Gradle builds started failing on every branch on Java 7 two days ago when TestNG released a new version (6.9.13) built with Java 8.
java.lang.UnsupportedClassVersionError: org/testng/ITestListener : Unsupported major.minor version 52.0

This can be seen e.g. here on CI: https://builds.gradle.org/viewLog.html?buildId=1322067

The root cause of this is that we use dynamic versions (latest.release) to resolve versions of librairies used in the build init templates. This is dangerous.
See https://github.com/gradle/gradle/blob/master/subprojects/build-init/build-init.gradle#L39-L84

As a quick fix for 3.1 we use fixed versions on the release branch. We need to think more holistically about that for
3.2.

gradle/build-tool-issues#302
+review REVIEW-6252