Don't load all annotations when checking nullability for fields and methods
Since if new annotation is added it might not be on the classpath and one can get java.lang.NoClassDefFoundError.
Parameter nullability check still uses old way, since it's a bit more complex and can be fixed if there is any issue with it in the future.