Fix classloader problem in TAPI integration test
- failure was
  NoClassDefFoundError: org/gradle/api/artifacts/ResolveException

- ToolingApiCompatibilitySuiteRunner / ToolingApiExecution
  has custom classloading to be able to run different Gradle
  versions. Referencing Gradle classes in TAPI integration test classes
  is not supported because of the custom classloading setup. It's
  easy to forget this because tests pass with the default test runner
  configuration, but fail with org.gradle.integtest.executer=forking.

+review REVIEW-6309 REVIEW-6315