Add transitive implementation dependencies to the PMD auxclasspath
Certain PMD diagnostics load classes referenced in the analyzed source
file, for example, to reconstruct type hierarchies. Such classes are
loaded from the auxclasspath. Prior to this CL only compile outputs and
compile classpath were used as auxclasspath. PMD was complaining about
missing class if some library on compile classpath was referencing other
class from its `implementation` dependency because Gradle doesn't add
transitive `implementation` dependencies to the compile classpath.

This CL introduces new internal configuration `sourcesetPmdAuxClasspath`
that extends compile classpath but is resolved as a runtime classpath
thus including all transitive `implementation` dependencies.

This CL doesn't cover all possible corner cases because referenced
classes from transitive `compileOnly` dependencies are not available.
An additional user-visible configuration `pmdAux` is added to work
around this. The user who encounters the NoClassDefFoundError due to
compileOnly dependency can add it to `pmdAux` configuration while
avoiding pollution of the compile classpath.

Fixes #17410

See https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#auxclasspath