Fix NoClassDefFoundError in performance test (#10153)
Fixes https://github.com/gradle/gradle-private/issues/1359

The problem is that TC returns a `text/html` HTTP response even when we explicitly set `Accept: application/json`. When this happens, the `NoClassDefFoundError` is expected because we excluded `xerces`.